  
title: Usman Khan
description: Hi! I'm Muhammad Usman. I am a Student of Computer Science in National University of Modern Languages,Islamabad. I am also a self taught python machine Learning Engineer. Subsequently I'm Persueing a certification in Artificial Intelligence by Presidential Initative for Artificial Intelligence and Computing. Morever I'm also working as a Technical/Database Operations Executive for Young's Pvt LTD. I have an excellent background in programming as well as cooredination and management

permalink: pretty

url: www.usmanniazi.me
twitter:
  username: UsmanNiazi99
  card: summary
 
social:
  name: Usman Khan
  links:
    - https://twitter.com/Usmanniazi99
    - https://www.facebook.com/UsmanNiazi99
    - https://www.linkedin.com/in/UsmanNiazi99  
    - https://github.com/UsmanNiazi
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-primer
